# Generated by Django 5.2.1 on 2025-05-08 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat', '0001_initial'),
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='logement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='locations.logement'),
        ),
    ]
